### ISSUE TITLE
maketni css qisimlarini Minifier  qilish kerak

### ISSUE THREAD

**Issue by frontendoniyorbek** [NodirXon0609/loopstudios#1]
[normalize.css](https://github.com/NodirXon0609/loopstudios/blob/main/css/normalize.css) hamda [styles.css](https://github.com/NodirXon0609/loopstudios/blob/main/css/styles.css)  shularni Minifier qilib qo'yish kerak

**Comment by NodirXon0609** [comment]
normalize.css va styles.css Minify qilindi.
