### ISSUE TITLE
footer qismida textga css berishda xato bor

### ISSUE THREAD

**Issue by frontendoniyorbek** [NodirXon0609/loopstudios#3]
https://github.com/NodirXon0609/loopstudios/blob/0068bcaa12fc747e72a332387cb332c4531d71bd/index.html#L169

buga css da stil berilyatganda **opacity: 0.5;** berilgan buning o'rniga rangini shfof qilgan avzal 
color: rgba(255, 255, 255, 0.5); shu ko'rinishda

**Comment by NodirXon0609** [comment]
opacity: 0.5 ni o'rniga rgba(255, 255, 255, 0.5) ni yozildi va muammo bartaraf qilindi
